### ISSUE TITLE
datasets not visible [Service Unavailable]

### ISSUE THREAD

**Issue by snehankitrd** [SemanticComputing/fuseki-docker#5]
ubuntu3@ubuntu3-VirtualBox:~$ sudo docker run --rm -it -p 3030:3030 --name fuseki -e ADMIN_PASSWORD=1 -e ENABLE_DATA_WRITE=true -e ENABLE_UPDATE=true -e ENABLE_UPLOAD=true -e QUERY_TIMEOUT=60000 --mount type=bind,source="$(pwd)"/fuseki-data,target=/fuseki-base/databases secoresearch/fuseki
###################################
Initializing Apache Jena Fuseki

###################################
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/jena-fuseki/fuseki-server.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/javalibs/silk-arq-1.0.0-SNAPSHOT-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
09:00:26 INFO  Server          :: Apache Jena Fuseki 3.17.0
09:00:26 INFO  Config          :: FUSEKI_HOME=/jena-fuseki
09:00:26 INFO  Config          :: FUSEKI_BASE=/fuseki-base
09:00:26 ERROR Server          :: Exception in server initialization
org.apache.jena.fuseki.FusekiConfigException: Not writable: /fuseki-base/databases
	at org.apache.jena.fuseki.webapp.FusekiWebapp.writeableDirectory(FusekiWebapp.java:399) ~[fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.webapp.FusekiWebapp.formatBaseArea(FusekiWebapp.java:150) [fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.webapp.ShiroEnvironmentLoader.contextInitialized(ShiroEnvironmentLoader.java:50) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1068) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:997) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1457) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1422) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:426) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.Server.start(Server.java:423) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.Server.doStart(Server.java:387) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.cmd.JettyFusekiWebapp.start(JettyFusekiWebapp.java:125) [fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.cmd.FusekiCmd.runFuseki(FusekiCmd.java:376) [fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.cmd.FusekiCmd$FusekiCmdInner.exec(FusekiCmd.java:360) [fuseki-server.jar:3.17.0]
	at jena.cmd.CmdMain.mainMethod(CmdMain.java:92) [fuseki-server.jar:3.17.0]
	at jena.cmd.CmdMain.mainRun(CmdMain.java:58) [fuseki-server.jar:3.17.0]
	at jena.cmd.CmdMain.mainRun(CmdMain.java:45) [fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.cmd.FusekiCmd$FusekiCmdInner.innerMain(FusekiCmd.java:105) [fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.cmd.FusekiCmd.main(FusekiCmd.java:68) [fuseki-server.jar:3.17.0]
09:00:26 WARN  WebAppContext   :: Failed startup of context o.e.j.w.WebAppContext@4b3c354a{Apache Jena Fuseki Server,/,file:///jena-fuseki/webapp/,UNAVAILABLE}
org.apache.jena.fuseki.FusekiConfigException: Not writable: /fuseki-base/databases
	at org.apache.jena.fuseki.webapp.FusekiWebapp.writeableDirectory(FusekiWebapp.java:399) ~[fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.webapp.FusekiWebapp.formatBaseArea(FusekiWebapp.java:150) ~[fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.webapp.ShiroEnvironmentLoader.contextInitialized(ShiroEnvironmentLoader.java:50) ~[fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1068) ~[fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572) ~[fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:997) ~[fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746) ~[fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379) ~[fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1457) ~[fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1422) ~[fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911) ~[fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:426) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.Server.start(Server.java:423) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.server.Server.doStart(Server.java:387) [fuseki-server.jar:3.17.0]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.cmd.JettyFusekiWebapp.start(JettyFusekiWebapp.java:125) [fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.cmd.FusekiCmd.runFuseki(FusekiCmd.java:376) [fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.cmd.FusekiCmd$FusekiCmdInner.exec(FusekiCmd.java:360) [fuseki-server.jar:3.17.0]
	at jena.cmd.CmdMain.mainMethod(CmdMain.java:92) [fuseki-server.jar:3.17.0]
	at jena.cmd.CmdMain.mainRun(CmdMain.java:58) [fuseki-server.jar:3.17.0]
	at jena.cmd.CmdMain.mainRun(CmdMain.java:45) [fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.cmd.FusekiCmd$FusekiCmdInner.innerMain(FusekiCmd.java:105) [fuseki-server.jar:3.17.0]
	at org.apache.jena.fuseki.cmd.FusekiCmd.main(FusekiCmd.java:68) [fuseki-server.jar:3.17.0]
09:00:26 INFO  Server          :: Started 2021/02/17 09:00:26 GMT on port 3030

**Comment by snehankitrd** [comment]
Change permission of $(pwd)"/fuseki-data to 777.
>chmod 777 fuseki-data/
